# .sync.yml
---
.gitignore:
  paths:
  - .ruby-version
  - .rspec_status
Gemfile:
  optional:
    ':default':
      - gem: 'dashboard-api'
      - gem: 'puppet-resource_api'
    ':development':
      - gem: 'codecov'
      - gem: 'simplecov-console'
spec/spec_helper.rb:
  mock_with: ':rspec'
